baseURL = 'https://nilpainter.github.io/'
languageCode = 'en-us'
title = 'Nil Painter'
theme = 'blowfish'

[module]
  [module.hugoVersion]
    extended = true
    min = "0.87.0"

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"
